import { Job } from "../../types/_types";

export const jobs = [
	{
		id: 1,
		title: "Frontend Developer",
		location: "Remote",
		company: "Google",
		hourlySalary: "£65",
		date: "4 days ago",
		description:
			"A frontend developer with experience in React.js, Vue.js, and Angular.js. Must have 3 years of experience.",
		types: ["full-time", "part-time"],
		status: "none",
	},
	{
		id: 2,
		title: "Backend Developer",
		location: "Onsite",
		company: "Facebook",
		hourlySalary: "£50",
		date: "5 days ago",
		description:
			"A backend developer with experience in Node.js, Python, and Ruby. Must have 3 years of experience.",
		types: ["full-time", "part-time"],
		status: "none",
	},
	{
		id: 3,
		title: "Fullstack Developer",
		location: "Hybrid",
		company: "Amazon",
		hourlySalary: "£34",
		date: "12 days ago",
		description:
			"A fullstack developer with experience in React.js, Vue.js, Angular.js, Node.js, Python, and Ruby.",
		types: ["full-time", "part-time"],
		status: "none",
	},
	{
		id: 4,
		title: "DevOps Engineer",
		location: "Hybrid",
		company: "Microsoft",
		hourlySalary: "£40",
		date: "15 days ago",
		description:
			"A devops engineer with experience in AWS, Azure, and GCP. Must have 3 years of experience.",
		types: ["full-time", "part-time"],
		status: "none",
	},
	{
		id: 5,
		title: "Data Scientist",
		location: "Remote",
		company: "Netflix",
		hourlySalary: "£450",
		date: "20 days ago",
		description:
			"A data scientist with experience in Python, R, and SQL. Must have 3 years of experience.",
		types: ["full-time", "part-time"],
		status: "none",
	},
	{
		id: 6,
		title: "UX/UI Designer",
		location: "Onsite",
		company: "Spotify",
		hourlySalary: "£40",
		date: "25 days ago",
		description:
			"A ux/ui designer with experience in Figma, Sketch, and Adobe XD. Must have 3 years of experience.",
		types: ["full-time", "part-time"],
		status: "none",
	},
	{
		id: 7,
		title: "Product Manager",
		location: "Onsite",
		company: "Apple",
		hourlySalary: "£19",
		date: "30 days ago",
		description:
			"A product manager with experience in Jira, Trello, and Asana. Must have 3 years of experience.",
		types: ["full-time", "part-time"],
		status: "none",
	},
	{
		id: 9,
		title: "QA Engineer",
		location: "Hybrid",
		company: "Twitter",
		hourlySalary: "£30",
		date: "40 days ago",
		description:
			"A qa engineer with experience in Selenium, Cypress, and Jest. Must have 3 years of experience.",
		types: ["full-time", "part-time"],
		status: "none",
	},
	{
		id: 10,
		title: "Security Engineer",
		location: "Remote",
		company: "LinkedIn",
		hourlySalary: "£40",
		date: "45 days ago",
		description:
			"A security engineer with experience in OWASP, NIST, and ISO 27001. Must have 3 years of experience.",
		types: ["full-time", "part-time"],
		status: "none",
	},
	{
		id: 11,
		title: "Network Engineer",
		location: "Remote",
		company: "Uber",
		hourlySalary: "£12",
		date: "50 days ago",
		description:
			"A network engineer with experience in Cisco, Juniper, and Arista. Must have 3 years of experience.",
		types: ["full-time", "part-time"],
		status: "none",
	},
	{
		id: 12,
		title: "Database Administrator",
		location: "Remote",
		company: "Airbnb",
		hourlySalary: "£18",
		date: "55 days ago",
		description:
			"A database administrator with experience in MySQL, PostgreSQL, and MongoDB.",
		types: ["full-time", "part-time"],
		status: "none",
	},
	{
		id: 13,
		title: "Cloud Engineer",
		location: "Remote",
		company: "Pinterest",
		hourlySalary: "£70",
		date: "60 days ago",
		description:
			"A cloud engineer with experience in AWS, Azure, and GCP. Must have 3 years of experience.",
		types: ["full-time", "part-time"],
		status: "none",
	},
	{
		id: 14,
		title: "Machine Learning Engineer",
		location: "Hybrid",
		company: "Snapchat",
		hourlySalary: "£18",
		date: "65 days ago",
		description:
			"A machine learning engineer with experience in TensorFlow, PyTorch, and Keras. Must have 3 years of experience.",
		types: ["full-time", "part-time"],
		status: "none",
	},
	{
		id: 15,
		title: "Artificial Intelligence Engineer",
		location: "Remote",
		company: "TikTok",
		hourlySalary: "£15",
		date: "70 days ago",
		description:
			"An artificial intelligence engineer with experience in TensorFlow, PyTorch, and Keras. Must have 3 years of experience.",
		types: ["full-time", "part-time"],
		status: "none",
	},
	{
		id: 16,
		title: "Blockchain Developer",
		location: "Remote",
		company: "Zoom",
		hourlySalary: "£50",
		date: "75 days ago",
		description:
			"A blockchain developer with experience in Ethereum, Solidity, and Hyperledger. Must have 3 years of experience.",
		types: ["full-time", "part-time"],
		status: "none",
	},
	{
		id: 17,
		title: "Cybersecurity Analyst",
		location: "Remote",
		company: "Slack",
		hourlySalary: "£20",
		date: "80 days ago",
		description:
			"A cybersecurity analyst with experience in OWASP, NIST, and ISO 27001. Must have 3 years of experience.",
		types: ["full-time", "part-time"],
		status: "none",
	},
	{
		id: 18,
		title: "Web Developer",
		location: "Onsite",
		company: "Adobe",
		hourlySalary: "£70",
		date: "85 days ago",
		description:
			"A web developer with experience in HTML, CSS, and JavaScript. Must have 3 years of experience.",
		types: ["full-time", "part-time"],
		status: "none",
	},
	{
		id: 19,
		title: "Mobile Developer",
		location: "Onsite",
		company: "Adobe",
		hourlySalary: "£60",
		date: "90 days ago",
		description:
			"A mobile developer with experience in React Native, Flutter, and Swift. Must have 3 years of experience.",
		types: ["full-time", "part-time"],
		status: "none",
	},
	{
		id: 20,
		title: "Game Developer",
		location: "Remote",
		company: "Adobe",
		hourlySalary: "£24",
		date: "95 days ago",
		description:
			"A game developer with experience in Unity, Unreal Engine, and Godot. Must have 3 years of experience.",
		types: ["full-time", "part-time"],
		status: "none",
	},
] as Job[];
